# Generated by Django 4.2.11 on 2024-04-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylistitem',
            name='per_measurement_unit_price',
        ),
    ]
