# Generated by Django 4.2.11 on 2024-04-17 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_grocerylist_total_price'),
        ('grocery_list_item', '0003_alter_grocerylistitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistitem',
            name='grocery_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grocery_list.grocerylist'),
        ),
    ]
