# Generated by Django 4.2.11 on 2024-04-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grocery_list_item", "0004_alter_grocerylistitem_grocery_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grocerylistitem",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
