# Generated by Django 4.2.11 on 2024-04-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
