# Generated by Django 4.2.11 on 2024-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_alter_grocerylist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
