# Generated by Django 5.0.3 on 2024-03-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listproduct",
            name="per_measurement_unit_price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listproduct",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
